# Random group generator for Latin-squaring
Table Creator for PennController Experiments

In [1]:
import pandas as pd
from pandas import DataFrame
from sklearn.preprocessing import scale
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import matplotlib as mpl 
import os
import csv
import itertools
from itertools import cycle
import string

In [2]:
# This makes the display show more info
pd.set_option('display.max_rows', None)
pd.set_option('display.max_colwidth', -1)

In [4]:
q = pd.read_csv("q_table.csv")

In [5]:
q.head()

,Unnamed: 0,QuestType,WhichQuestion,WhichAnswer,verb,Matrix,ImageName,MOAnswer,MSAnswer,MAAnswer,MFAnswer,ModQuest,NoModQuest,Group
0,0,1,Mod,MO,know,Irene knows,red1.png,A,A and B,"A, B, D, and F",C,ho can play a red card?,ho has a red card to play?,A
1,1,1,Mod,MO,know,Irene knows,red2.png,F,D and F,"B, C, D, and F",A,ho can play a red card?,ho has a red card to play?,A
2,2,1,Mod,MO,know,Irene knows,black1.png,D,B and D,"A, B, D, and F",C,ho can play a black card?,ho has a black card to play?,B
3,3,1,Mod,MO,know,Irene knows,black2.png,B,B and C,"B, C, D, and F",E,ho can play a black card?,ho has a black card to play?,B
4,4,1,Mod,MO,know,Irene knows,spade1.png,C,B and C,"B, C, E, and F",A,ho can play a spade?,ho has a spade to play?,C

In [9]:
q['ModQuest'] = q['ModQuest'].str.replace('?', '')
q['NoModQuest'] = q['NoModQuest'].str.replace('?', '')

# Bott and Noveck

In [11]:
q.to_csv("q_table.csv", header=True)

In [344]:
bn_facts = pd.read_csv("bn_facts.csv")
bn_latin = pd.read_csv("bn_latin.csv")

In [395]:
bl = pd.melt(bn_latin, id_vars=['Token','MatchingCategory','MismatchingCategory'], var_name='Group',value_name='SentNumber')
bn_all = pd.merge(bn_facts,bl, on="SentNumber")

In [430]:
bn_all = bn_all.drop(["Group_x"], axis=1).rename(columns={'Group_y':'Group'})

In [407]:
len(bn_all.loc[bn_all.Group_y == "A"])

36

In [410]:
bn_all.groupby(["Group_y","Token"])["Group_y"].count()

Group_y  Token
A        alligators      1
         anchovies       1
         ants            1
         apples          1
         bananas         1
         canaries        1
         carp            1
         cats            1
         chameleons      1
         cicadas         1
         cockroaches     1
         cod             1
         crocodiles      1
         crows           1
         dogs            1
         doves           1
         eagles          1
         elephants       1
         flies           1
         geckos          1
         herring         1
         horses          1
         iguanas         1
         lizards         1
         mackerels       1
         mosquitos       1
         owls            1
         peaches         1
         pears           1
         pigs            1
         piranhas        1
         plums           1
         sheep           1
         sparrows        1
         strawberries    1
         wasps           1
B        alligators      1
         anchovies       1
         ants            1
         apples          1
         bananas         1
         canaries        1
         carp            1
         cats            1
         chameleons      1
         cicadas         1
         cockroaches     1
         cod             1
         crocodiles      1
         crows           1
         dogs            1
         doves           1
         eagles          1
         elephants       1
         flies           1
         geckos          1
         herring         1
         horses          1
         iguanas         1
         lizards         1
         mackerels       1
         mosquitos       1
         owls            1
         peaches         1
         pears           1
         pigs            1
         piranhas        1
         plums           1
         sheep           1
         sparrows        1
         strawberries    1
         wasps           1
C        alligators      1
         anchovies       1
         ants            1
         apples          1
         bananas         1
         canaries        1
         carp            1
         cats            1
         chameleons      1
         cicadas         1
         cockroaches     1
         cod             1
         crocodiles      1
         crows           1
         dogs            1
         doves           1
         eagles          1
         elephants       1
         flies           1
         geckos          1
         herring         1
         horses          1
         iguanas         1
         lizards         1
         mackerels       1
         mosquitos       1
         owls            1
         peaches         1
         pears           1
         pigs            1
         piranhas        1
         plums           1
         sheep           1
         sparrows        1
         strawberries    1
         wasps           1
D        alligators      1
         anchovies       1
         ants            1
         apples          1
         bananas         1
         canaries        1
         carp            1
         cats            1
         chameleons      1
         cicadas         1
         cockroaches     1
         cod             1
         crocodiles      1
         crows           1
         dogs            1
         doves           1
         eagles          1
         elephants       1
         flies           1
         geckos          1
         herring         1
         horses          1
         iguanas         1
         lizards         1
         mackerels       1
         mosquitos       1
         owls            1
         peaches         1
         pears           1
         pigs            1
         piranhas        1
         plums           1
         sheep           1
         sparrows        1
         strawberries    1
         wasps           1
E        alligators      1
         anchovies       1
         ants            1
         apples          1
         bananas         1
         canaries        1
         carp            1
         cats            1
         chameleons      1
         cicadas         1
         cockroaches     1
         cod             1
         crocodiles      1
         crows           1
         dogs            1
         doves           1
         eagles          1
         elephants       1
         flies           1
         geckos          1
         herring         1
         horses          1
         iguanas         1
         lizards         1
         mackerels       1
         mosquitos       1
         owls            1
         peaches         1
         pears           1
         pigs            1
         piranhas        1
         plums           1
         sheep           1
         sparrows        1
         strawberries    1
         wasps           1
F        alligators      1
         anchovies       1
         ants            1
         apples          1
         bananas         1
         canaries        1
         carp            1
         cats            1
         chameleons      1
         cicadas         1
         cockroaches     1
         cod             1
         crocodiles      1
         crows           1
         dogs            1
         doves           1
         eagles          1
         elephants       1
         flies           1
         geckos          1
         herring         1
         horses          1
         iguanas         1
         lizards         1
         mackerels       1
         mosquitos       1
         owls            1
         peaches         1
         pears           1
         pigs            1
         piranhas        1
         plums           1
         sheep           1
         sparrows        1
         strawberries    1
         wasps           1
G        alligators      1
         anchovies       1
         ants            1
         apples          1
         bananas         1
         canaries        1
         carp            1
         cats            1
         chameleons      1
         cicadas         1
         cockroaches     1
         cod             1
         crocodiles      1
         crows           1
         dogs            1
         doves           1
         eagles          1
         elephants       1
         flies           1
         geckos          1
         herring         1
         horses          1
         iguanas         1
         lizards         1
         mackerels       1
         mosquitos       1
         owls            1
         peaches         1
         pears           1
         pigs            1
         piranhas        1
         plums           1
         sheep           1
         sparrows        1
         strawberries    1
         wasps           1
H        alligators      1
         anchovies       1
         ants            1
         apples          1
         bananas         1
         canaries        1
         carp            1
         cats            1
         chameleons      1
         cicadas         1
         cockroaches     1
         cod             1
         crocodiles      1
         crows           1
         dogs            1
         doves           1
         eagles          1
         elephants       1
         flies           1
         geckos          1
         herring         1
         horses          1
         iguanas         1
         lizards         1
         mackerels       1
         mosquitos       1
         owls            1
         peaches         1
         pears           1
         pigs            1
         piranhas        1
         plums           1
         sheep           1
         sparrows        1
         strawberries    1
         wasps           1
I        alligators      1
         anchovies       1
         ants            1
         apples          1
         bananas         1
         canaries        1
         carp            1
         cats            1
         chameleons      1
         cicadas         1
         cockroaches     1
         cod             1
         crocodiles      1
         crows           1
         dogs            1
         doves           1
         eagles          1
         elephants       1
         flies           1
         geckos          1
         herring         1
         horses          1
         iguanas         1
         lizards         1
         mackerels       1
         mosquitos       1
         owls            1
         peaches         1
         pears           1
         pigs            1
         piranhas        1
         plums           1
         sheep           1
         sparrows        1
         strawberries    1
         wasps           1
J        alligators      1
         anchovies       1
         ants            1
         apples          1
         bananas         1
         canaries        1
         carp            1
         cats            1
         chameleons      1
         cicadas         1
         cockroaches     1
         cod             1
         crocodiles      1
         crows           1
         dogs            1
         doves           1
         eagles          1
         elephants       1
         flies           1
         geckos          1
         herring         1
         horses          1
         iguanas         1
         lizards         1
         mackerels       1
         mosquitos       1
         owls            1
         peaches         1
         pears           1
         pigs            1
         piranhas        1
         plums           1
         sheep           1
         sparrows        1
         strawberries    1
         wasps           1
K        alligators      1
         anchovies       1
         ants            1
         apples          1
         bananas         1
         canaries        1
         carp            1
         cats            1
         chameleons      1
         cicadas         1
         cockroaches     1
         cod             1
         crocodiles      1
         crows           1
         dogs            1
         doves           1
         eagles          1
         elephants       1
         flies           1
         geckos          1
         herring         1
         horses          1
         iguanas         1
         lizards         1
         mackerels       1
         mosquitos       1
         owls            1
         peaches         1
         pears           1
         pigs            1
         piranhas        1
         plums           1
         sheep           1
         sparrows        1
         strawberries    1
         wasps           1
L        alligators      1
         anchovies       1
         ants            1
         apples          1
         bananas         1
         canaries        1
         carp            1
         cats            1
         chameleons      1
         cicadas         1
         cockroaches     1
         cod             1
         crocodiles      1
         crows           1
         dogs            1
         doves           1
         eagles          1
         elephants       1
         flies           1
         geckos          1
         herring         1
         horses          1
         iguanas         1
         lizards         1
         mackerels       1
         mosquitos       1
         owls            1
         peaches         1
         pears           1
         pigs            1
         piranhas        1
         plums           1
         sheep           1
         sparrows        1
         strawberries    1
         wasps           1
M        alligators      1
         anchovies       1
         ants            1
         apples          1
         bananas         1
         canaries        1
         carp            1
         cats            1
         chameleons      1
         cicadas         1
         cockroaches     1
         cod             1
         crocodiles      1
         crows           1
         dogs            1
         doves           1
         eagles          1
         elephants       1
         flies           1
         geckos          1
         herring         1
         horses          1
         iguanas         1
         lizards         1
         mackerels       1
         mosquitos       1
         owls            1
         peaches         1
         pears           1
         pigs            1
         piranhas        1
         plums           1
         sheep           1
         sparrows        1
         strawberries    1
         wasps           1
N        alligators      1
         anchovies       1
         ants            1
         apples          1
         bananas         1
         canaries        1
         carp            1
         cats            1
         chameleons      1
         cicadas         1
         cockroaches     1
         cod             1
         crocodiles      1
         crows           1
         dogs            1
         doves           1
         eagles          1
         elephants       1
         flies           1
         geckos          1
         herring         1
         horses          1
         iguanas         1
         lizards         1
         mackerels       1
         mosquitos       1
         owls            1
         peaches         1
         pears           1
         pigs            1
         piranhas        1
         plums           1
         sheep           1
         sparrows        1
         strawberries    1
         wasps           1
O        alligators      1
         anchovies       1
         ants            1
         apples          1
         bananas         1
         canaries        1
         carp            1
         cats            1
         chameleons      1
         cicadas         1
         cockroaches     1
         cod             1
         crocodiles      1
         crows           1
         dogs            1
         doves           1
         eagles          1
         elephants       1
         flies           1
         geckos          1
         herring         1
         horses          1
         iguanas         1
         lizards         1
         mackerels       1
         mosquitos       1
         owls            1
         peaches         1
         pears           1
         pigs            1
         piranhas        1
         plums           1
         sheep           1
         sparrows        1
         strawberries    1
         wasps           1
P        alligators      1
         anchovies       1
         ants            1
         apples          1
         bananas         1
         canaries        1
         carp            1
         cats            1
         chameleons      1
         cicadas         1
         cockroaches     1
         cod             1
         crocodiles      1
         crows           1
         dogs            1
         doves           1
         eagles          1
         elephants       1
         flies           1
         geckos          1
         herring         1
         horses          1
         iguanas         1
         lizards         1
         mackerels       1
         mosquitos       1
         owls            1
         peaches         1
         pears           1
         pigs            1
         piranhas        1
         plums           1
         sheep           1
         sparrows        1
         strawberries    1
         wasps           1
Q        alligators      1
         anchovies       1
         ants            1
         apples          1
         bananas         1
         canaries        1
         carp            1
         cats            1
         chameleons      1
         cicadas         1
         cockroaches     1
         cod             1
         crocodiles      1
         crows           1
         dogs            1
         doves           1
         eagles          1
         elephants       1
         flies           1
         geckos          1
         herring         1
         horses          1
         iguanas         1
         lizards         1
         mackerels       1
         mosquitos       1
         owls            1
         peaches         1
         pears           1
         pigs            1
         piranhas        1
         plums           1
         sheep           1
         sparrows        1
         strawberries    1
         wasps           1
R        alligators      1
         anchovies       1
         ants            1
         apples          1
         bananas         1
         canaries        1
         carp            1
         cats            1
         chameleons      1
         cicadas         1
         cockroaches     1
         cod             1
         crocodiles      1
         crows           1
         dogs            1
         doves           1
         eagles          1
         elephants       1
         flies           1
         geckos          1
         herring         1
         horses          1
         iguanas         1
         lizards         1
         mackerels       1
         mosquitos       1
         owls            1
         peaches         1
         pears           1
         pigs            1
         piranhas        1
         plums           1
         sheep           1
         sparrows        1
         strawberries    1
         wasps           1
Name: Group_y, dtype: int64

In [432]:
bn_all.to_csv("bn_table.csv", header=True)

# Chemla and Bott

In [412]:
cb_latin = pd.read_csv("cb_latin.csv")
cb_facts = pd.read_csv("cb_facts.csv")

In [413]:
cl = pd.melt(cb_latin, id_vars=['Token','MatchingCategory','MismatchingCategory'], var_name='Group',value_name='SentNumber')
cb_all = pd.merge(cb_facts,cl, on="SentNumber")

In [434]:
cb_all = cb_all.drop(["Group_x"], axis=1).rename(columns={'Group_y':'Group'})

In [435]:
cb_all.to_csv("cb_table.csv", header=True)

# Questions

In [415]:
q_facts = pd.read_csv("q_facts.csv")
q_latin = pd.read_csv("q_latin.csv")

In [424]:
ql = pd.melt(q_latin, id_vars=['ImageName','MO','MS','MA','MF','ModQuest','NoModQuest'], var_name='Group',value_name='QuestType')
q_all = pd.merge(q_facts,ql, on="QuestType")

In [439]:
len(q_all.loc[q_all.Group == "A"])

32

In [440]:
q_all.loc[q_all.Group == "A"]

,QuestType,WhichQuestion,WhichAnswer,verb,Matrix,ImageName,MO,MS,MA,MF,ModQuest,NoModQuest,Group
0,1,ModQuest,MO,know,Irene knows,red1.png,A,A and B,"A, B, D, and F",C,Who can play a red card?,Who has a red card to play?,A
1,1,ModQuest,MO,know,Irene knows,red2.png,F,D and F,"B, C, D, and F",A,Who can play a red card?,Who has a red card to play?,A
32,2,ModQuest,MS,know,Irene knows,black1.png,D,B and D,"A, B, D, and F",C,Who can play a black card?,Who has a black card to play?,A
33,2,ModQuest,MS,know,Irene knows,black2.png,B,B and C,"B, C, D, and F",E,Who can play a black card?,Who has a black card to play?,A
64,3,ModQuest,MA,know,Irene knows,spade1.png,C,B and C,"B, C, E, and F",A,Who can play a spade?,Who has a spade to play?,A
65,3,ModQuest,MA,know,Irene knows,spade2.png,E,B and E,"A, B, C, and E",D,Who can play a spade?,Who has a spade to play?,A
96,4,ModQuest,MF,know,Irene knows,club1.png,A,A and C,"A, C, D, and F",B,Who can play a club?,Who has a club to play?,A
97,4,ModQuest,MF,know,Irene knows,club2.png,C,B and C,"B, C, D, and E",F,Who can play a club?,Who has a club to play?,A
128,5,ModQuest,MO,say,Irene said,diamond1.png,E,D and E,"A, B, D, and E",C,Who can play a diamond?,Who has a diamond to play?,A
129,5,ModQuest,MO,say,Irene said,diamond2.png,A,A and B,"A, B, E, and F",C,Who can play a diamond?,Who has a diamond to play?,A
160,6,ModQuest,MS,say,Irene said,heart1.png,F,C and F,"A, C, D, and F",B,Who can play a heart?,Who has a hear to play?,A
161,6,ModQuest,MS,say,Irene said,heart2.png,B,B and E,"A, B, C, and E",D,Who can play a heart?,Who has a hear to play?,A
192,7,ModQuest,MA,say,Irene said,jack1.png,A,A and B,"A, B, D, and F",E,Who can play a jack?,Who has a jack to play?,A
193,7,ModQuest,MA,say,Irene said,jack2.png,A,A and C,"A, C, E, and F",B,Who can play a jack?,Who has a jack to play?,A
224,8,ModQuest,MF,say,Irene said,queen1.png,B,B and C,"A, B, C, and E",D,Who can play a queen?,Who has a queen to play?,A
225,8,ModQuest,MF,say,Irene said,queen2.png,F,E and F,"B, C, E, and F",A,Who can play a queen?,Who has a queen to play?,A
256,9,NoModQuest,MO,know,Irene knows,king1.png,D,D and E,"A, B, D, and E",C,Who can play a king?,Who has a king to play?,A
257,9,NoModQuest,MO,know,Irene knows,king2.png,C,C and D,"A, C, D, and F",E,Who can play a king?,Who has a king to play?,A
288,10,NoModQuest,MS,know,Irene knows,face1.png,C,C and D,"A, C, D, and E",F,Who can play a face card?,Who hasa face card to play?,A
289,10,NoModQuest,MS,know,Irene knows,face2.png,B,B and C,"B, C, D, and F",A,Who can play a face card?,Who hasa face card to play?,A
320,11,NoModQuest,MA,know,Irene knows,number1.png,F,C and F,"C, D, E, and F",A,Who can play a number card?,Who has a number card to play?,A
321,11,NoModQuest,MA,know,Irene knows,number2.png,A,A and B,"A, B, D, and F",C,Who can play a number card?,Who has a number card to play?,A
352,12,NoModQuest,MF,know,Irene knows,ace1.png,B,B and C,"B, C, E, and F",D,Who can play an ace?,Who has an ace to play?,A
353,12,NoModQuest,MF,know,Irene knows,ace2.png,E,C and E,"A, B, C, and E",D,Who can play an ace?,Who has an ace to play?,A
384,13,NoModQuest,MO,say,Irene said,ten1.png,C,C and D,"B, C, D, and F",E,Who can play a ten?,Who has a ten to play?,A
385,13,NoModQuest,MO,say,Irene said,ten2.png,F,A and F,"A, B, E, and F",C,Who can play a ten?,Who has a ten to play?,A
416,14,NoModQuest,MS,say,Irene said,eight1.png,D,B and D,"B, C, D, and E",A,Who can play a eight?,Who has an eight to play?,A
417,14,NoModQuest,MS,say,Irene said,eight2.png,B,A and B,"A, B, D, and E",F,Who can play a eight?,Who has an eight to play?,A
448,15,NoModQuest,MA,say,Irene said,six1.png,A,A and B,"A, B, C, and F",D,Who can play a six?,Who has a six to play?,A
449,15,NoModQuest,MA,say,Irene said,six2.png,D,D and E,"B, D, E, and F",A,Who can play a six?,Who has a six to play?,A
480,16,NoModQuest,MF,say,Irene said,four1.png,F,A and F,"A, B, D, and F",E,Who can play a four?,Who has a four to play?,A
481,16,NoModQuest,MF,say,Irene said,four2.png,E,B and E,"B, D, E, and F",C,Who can play a four?,Who has a four to play?,A

In [441]:
q_all.to_csv("q_table.csv", header=True)

# Previous attempts

In [150]:
# Create a temporary column to merge on
cb_facts["temp"] = "1"
cb_cats["temp"] = "1"

In [155]:
cb_table = pd.merge(cb_facts,cb_cats, on="temp").drop(["temp","Group"], axis=1).rename(columns={"Token_x" :"Token"})
# Add the group column at the end.
cb_table["Group"] = ""
# Save the column names as a variable to put back in later
cb_names = cb_table.columns

In [270]:
# cb_table

### Convert to list

In [159]:
# convert the df to list
cb_list = []
for index,rows in cb_table.iterrows():
    my_list =[rows.SentNumber, rows.Verb, rows.WhichCategory, rows.Matrix, rows.Subject, 
              rows.Predicate, rows.SentType, rows.Negation, rows.CompTruth, rows.SubStat,
              rows.Token, rows.MatchingCategory, rows.MismatchingCategory]
    
    cb_list.append(my_list)

In [161]:
len(cb_list)

162

In [271]:
# cb_table

### Add groups

In [172]:
# Make a list of the Alphabet for the number of Lists in the Latin Square
alphabets = string.ascii_uppercase
Group = []
for i in alphabets:
    Group.append(i)
Group = Group[0:9]

In [277]:
# Group

In [174]:
test = list(zip(cb_list, cycle(Group)))
test = pd.DataFrame(test)

In [272]:
# test.head()

### Separate out all the factors

In [179]:
b = test[0].apply(pd.Series).merge(test, left_index = True, right_index = True).drop(["0_y"], axis = 1)
# add in the column names
b.columns = cb_names

In [274]:
# b.loc[b.Group == "B"]

### Save to .csv

In [187]:
b.to_csv("cb_table.csv", header=True)

In [231]:
# create a temporary column on both dfs to use in merge, to be deleted later
q_facts["temp"] = "1"
q_cats["temp"] = "1"

In [249]:
q_table = pd.merge(q_facts,q_cats, on="temp").drop(["temp"], axis=1).rename(columns={"Token_x" :"Token"})
# Add the group column at the end.
q_table["Group"] = ""
# Save the column names to be added back in later
q_names = q_table.columns

In [275]:
# q_table

### Convert to list

In [252]:
# convert the df to list
q_list = []
for index,rows in q_table.iterrows():
    my_list =[rows.QuestType, rows.WhichQuestion, rows.WhichAnswer, rows.verb, rows.Matrix, 
              rows.ImageName, rows.MO, rows.MS, rows.MA, rows.MF, rows.ModQuest, rows.NoModQuest]
    
    q_list.append(my_list)

In [253]:
len(q_list)

512

### Add groups

In [254]:
# Make a list of the Alphabet for the number of Lists in the Latin Square
alphabets = string.ascii_uppercase
Group = []
for i in alphabets:
    Group.append(i)
Group = Group[0:16]

In [266]:
# Group

In [256]:
test = list(zip(q_list, cycle(Group)))
test = pd.DataFrame(test)

In [267]:
# test.head()

### Separate out all the factors into separate columns

In [259]:
q = test[0].apply(pd.Series).merge(test, left_index = True, right_index = True).drop(["0_y"], axis = 1)
# Add the column names
q.columns = q_names

In [265]:
# q.loc[q.Group == "P"]

### Save to .csv

In [187]:
q.to_csv("q_table.csv", header=True)

In [345]:
bn_facts["temp"] = "1"
bn_cats["temp"] = "1"

Add the two .csv files together in the right way

In [346]:
bn_table = pd.merge(bn_facts,bn_cats, on="temp").drop("temp", axis=1).rename(columns={"Token_x" :"Token"})
# bn_table.to_csv("bn_table.csv", header=True)

In [347]:
bn_table = bn_table.drop(columns=["Group"])
bn_table["Group"] = ""

In [359]:
# convert the df to list
bn_list = []
for index,rows in bn_table.iterrows():
    my_list =[rows.SentNumber, rows.Quantifier, rows.Matrix, rows.WhichCategory, rows.Subject, rows.Predicate,
              rows.SentType, rows.Verb, rows.Embedded, rows.Token, rows.MatchingCategory, rows.MismatchingCategory]
    
    bn_list.append(my_list)

 Get a list of the letters which will be the different group names

In [322]:
# Make a list of the Alphabet 
alphabets = string.ascii_uppercase
Group = []
for i in alphabets:
    Group.append(i)
Group = Group[0:18]

In [323]:
# this is very close, but it's returning 72 items rather than 36
test = list(zip(bn_list, cycle(Group)))
test = pd.DataFrame(test)

In [324]:
test.head()

,0,1
0,"[alligators, reptiles, mamals, 1, some, nan, Matching, Token, Category, T1, none, 0]",A
1,"[crocodiles, reptiles, mamals, 1, some, nan, Matching, Token, Category, T1, none, 0]",B
2,"[chameleons, reptiles, mamals, 1, some, nan, Matching, Token, Category, T1, none, 0]",C
3,"[iguanas, reptiles, mamals, 1, some, nan, Matching, Token, Category, T1, none, 0]",D
4,"[lizards, reptiles, mamals, 1, some, nan, Matching, Token, Category, T1, none, 0]",E

In [325]:
# Make sure that each letter has 36 elements
len(test.loc[test[1] == "A"])

36

## Working through the

In [388]:
# try to sort the df on certain values
names = bn_table.columns
bn_table2 = bn_table.sort_values(["SentNumber","SentType"])#,"MatchingCategory","Token"])
# convert the df to list
bn_list2 = []
for index,rows in bn_table2.iterrows():
    my_list =[rows.SentNumber, rows.Quantifier, rows.Matrix, rows.WhichCategory, rows.Subject, rows.Predicate,
              rows.SentType, rows.Verb, rows.Embedded, rows.Token, rows.MatchingCategory, rows.MismatchingCategory]
    
    bn_list2.append(my_list)
# Zip the list with the Group    
test2 = list(zip(bn_list2, cycle(Group)))
test2 = pd.DataFrame(test2)
print(len(test2.loc[test2[1] == "A"]))
# test2.loc[test2[1] == "A"]

36

In [389]:
# test2.loc[test2[1] == "B"]

In [390]:
b2 = test2[0].apply(pd.Series).merge(test2, left_index = True, right_index = True).drop(["0_y"], axis = 1)
b2.columns = names

In [391]:
b2.groupby(["Group","Token"])["Group"].count()

Group  Token
A      alligators      18
       cats            18
B      crocodiles      18
       horses          18
C      chameleons      18
       dogs            18
D      iguanas         18
       pigs            18
E      elephants       18
       lizards         18
F      geckos          18
       sheep           18
G      anchovies       18
       wasps           18
H      carp            18
       cockroaches     18
I      cicadas         18
       cod             18
J      ants            18
       piranhas        18
K      flies           18
       mackerels       18
L      herring         18
       mosquitos       18
M      eagles          18
       strawberries    18
N      bananas         18
       canaries        18
O      apples          18
       crows           18
P      owls            18
       peaches         18
Q      pears           18
       sparrows        18
R      doves           18
       plums           18
Name: Group, dtype: int64

In [394]:
bn_latin.head()

,Token,MatchingCategory,MismatchingCategory,A,B,C,D,E,F,G,...,I,J,K,L,M,N,O,P,Q,R
0,alligators,reptiles,mamals,1,18,17,16,15,14,13,...,11,10,9,8,7,6,5,4,3,2
1,crocodiles,reptiles,mamals,2,1,18,17,16,15,14,...,12,11,10,9,8,7,6,5,4,3
2,chameleons,reptiles,mamals,3,2,1,18,17,16,15,...,13,12,11,10,9,8,7,6,5,4
3,iguanas,reptiles,mamals,4,3,2,1,18,17,16,...,14,13,12,11,10,9,8,7,6,5
4,lizards,reptiles,mamals,5,4,3,2,1,18,17,...,15,14,13,12,11,10,9,8,7,6

In [337]:
new = []
# Append the value of Group to the sub-list
for ind, i in enumerate(bn_list2):
# for i, ind in enumerate(bn_list):
    # Counter for bn_list
    # Start at 1, for SentType (1 out of 36)
    n=0 
    # Counter for Group
    # Start at -1, so then can increment +1 to get 'A' which is at index 0 
    k=-1 

    if i[3] == n+1: 
        i.append(Group[k+1])
        new.append(i)
        print(ind)
    print(len(new))
new_df = pd.DataFrame(new)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35

In [104]:
b = test[0].apply(pd.Series).merge(test, left_index = True, right_index = True).drop(["0_y",12], axis = 1)

In [ ]:
# b = b.drop([12], axis=1)

In [126]:
name1 = ['Token', 'MatchingCategory', 'MismatchingCategory','SentNumber','Quantifier','Matrix','WhichCategory','Subject','Predicate','SentType','Verb','Embedded','Group']

In [141]:
b.columns = name1

In [144]:
len(b)

647

In [269]:
# b.groupby(["Group"])["Group"].count()

In [268]:
# b.loc[b.Group == "B"]

### Save to .csv

In [148]:
b.to_csv("bn_table.csv", header=True)